version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  films:
    build:
      context: ./
      dockerfile: ./film-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/app # any change to base folder should be reflected
      - /app/node_modules    
    command: npm run start     

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
      - films
    volumes:
      - .:/app # any change to base folder should be reflected
      - /app/node_modules
    command: npm run start

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data